// ===== CONSTANTS =====
export const VETERINARY_CONSTANTS = {
    WORKFLOW_STEPS: {
        RECEPTION: 'reception',
        EXTERNAL_VERIFICATION: 'external',
        SLAUGHTER: 'slaughter',
        INTERNAL_VERIFICATION: 'internal',
        SHIPPING: 'shipping',
    },

    CERTIFICATE_STATUS: {
        ACTIVE: 'ACTIVE',
        EXPIRED: 'EXPIRED',
        PROCESSED: 'PROCESSED',
        CANCELLED: 'CANCELLED',
    },

    INSPECTION_RESULTS: {
        SUITABLE_FOR_SLAUGHTER: 'SUITABLE_FOR_SLAUGHTER',
        UNFIT_CONFISCATION: 'UNFIT_CONFISCATION',
        UNFIT_RETURN: 'UNFIT_RETURN',
        QUARANTINE: 'QUARANTINE',
    },

    PRODUCT_CLASSIFICATIONS: {
        SUITABLE_FOR_CONSUMPTION: 'SUITABLE_FOR_CONSUMPTION',
        SUITABLE_FOR_PROCESSING: 'SUITABLE_FOR_PROCESSING',
        TOTAL_CONFISCATION: 'TOTAL_CONFISCATION',
        PARTIAL_CONFISCATION: 'PARTIAL_CONFISCATION',
    },

    SHIPPING_STATUS: {
        PREPARATION: 'PREPARATION',
        IN_TRANSIT: 'IN_TRANSIT',
        DELIVERED: 'DELIVERED',
        RETURNED: 'RETURNED',
        INCIDENT: 'INCIDENT',
    },

    TEMPERATURE_RANGES: {
        REFRIGERATED: { min: -2, max: 4 },
        FROZEN: { min: -18, max: -15 },
        AMBIENT: { min: 15, max: 25 },
    },

    ANIMAL_TYPES: {
        BOVINE: 'Bovino',
        PORK: 'Porcino',
        POULTRY: 'Aviar',
        SHEEP: 'Ovino',
        GOAT: 'Caprino',
    },

    REPORT_TYPES: {
        DAILY: 'DAILY',
        WEEKLY: 'WEEKLY',
        MONTHLY: 'MONTHLY',
        CUSTOM: 'CUSTOM',
        CERTIFICATE_SUMMARY: 'CERTIFICATE_SUMMARY',
        INSPECTION_REPORT: 'INSPECTION_REPORT',
        PRODUCTION_REPORT: 'PRODUCTION_REPORT',
    },
};
